### ISSUE TITLE
How to enable Chromecast

### ISSUE THREAD

**Issue by Nickbert7** [henniaufmrenni/boum#66]
Is there any special tweak needed to enable Chromecast?
I also tried to set the address manually within the settings, but the icon stays grayed out.
![Screenshot_20221214-235022_boum.png](https://user-images.githubusercontent.com/14938497/207732503-0a35cd72-2fdc-4804-a6b8-479f1c3feb1a.png)

**Comment by henniaufmrenni** [comment]
Setting and enabling a different Chromecast adress is only for cases where you're using Chromecast outside of your home network. A use case for this feature can be found [here](https://github.com/henniaufmrenni/boum/blob/main/DOCUMENTATION.md#chromecast). 

In the usual case where your phone, the Jellyfin server and the Chromecast device are on the same network leave the setting "Different Chromecast Adress" disabled. The Chromecastcast icon should turn white and you'll be able to select the Chromecast device to cast to. 
If it isn't working, **leaving the app and coming back** helps for refreshing the state of the button. Not sure why though, since we're [using](https://github.com/henniaufmrenni/boum/blob/a8b631374bbd3c2177370b064e17950eac5879ec/app/components/Cast/CastButton.tsx#L4) the unmodified button from the cast library.

**Comment by Nickbert7** [comment]
Really strange, when I got home today it was suddenly working...
Nevertheless, thank you for the information.
